package redhat.insurance.prefildriverlist;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("Driver")
public class Driver implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "Name")
   private java.lang.String name;
   @org.kie.api.definition.type.Label(value = "Driver License Number")
   private java.lang.String driverLicenseNumber;
   @org.kie.api.definition.type.Label(value = "Date of Birth")
   private java.util.Date dateOfBirth;
   @org.kie.api.definition.type.Label(value = "Duplicate?")
   private boolean duplicate;
   @org.kie.api.definition.type.Label(value = "Age")
   private java.lang.Integer age;
   @org.kie.api.definition.type.Label(value = "Rating")
   private int rating;

   public Driver()
   {
   }

   public java.lang.String getName()
   {
      return this.name;
   }

   public void setName(java.lang.String name)
   {
      this.name = name;
   }

   public java.lang.String getDriverLicenseNumber()
   {
      return this.driverLicenseNumber;
   }

   public void setDriverLicenseNumber(java.lang.String driverLicenseNumber)
   {
      this.driverLicenseNumber = driverLicenseNumber;
   }

   public java.util.Date getDateOfBirth()
   {
      return this.dateOfBirth;
   }

   public void setDateOfBirth(java.util.Date dateOfBirth)
   {
      this.dateOfBirth = dateOfBirth;
   }

   public boolean isDuplicate()
   {
      return this.duplicate;
   }

   public void setDuplicate(boolean duplicate)
   {
      this.duplicate = duplicate;
   }

   public java.lang.Integer getAge()
   {
      return this.age;
   }

   public void setAge(java.lang.Integer age)
   {
      this.age = age;
   }

   public int getRating()
   {
      return this.rating;
   }

   public void setRating(int rating)
   {
      this.rating = rating;
   }

   public Driver(java.lang.String name, java.lang.String driverLicenseNumber,
         java.util.Date dateOfBirth, boolean duplicate,
         java.lang.Integer age, int rating)
   {
      this.name = name;
      this.driverLicenseNumber = driverLicenseNumber;
      this.dateOfBirth = dateOfBirth;
      this.duplicate = duplicate;
      this.age = age;
      this.rating = rating;
   }

}