package redhat.insurance.prefildriverlist;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Rating implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "Rating")
   private java.lang.Integer rating;
   @org.kie.api.definition.type.Label(value = "Driver")
   private redhat.insurance.prefildriverlist.Driver driver;

   public Rating()
   {
   }

   public java.lang.Integer getRating()
   {
      return this.rating;
   }

   public void setRating(java.lang.Integer rating)
   {
      this.rating = rating;
   }

   public redhat.insurance.prefildriverlist.Driver getDriver()
   {
      return this.driver;
   }

   public void setDriver(redhat.insurance.prefildriverlist.Driver driver)
   {
      this.driver = driver;
   }

   public Rating(java.lang.Integer rating,
         redhat.insurance.prefildriverlist.Driver driver)
   {
      this.rating = rating;
      this.driver = driver;
   }

}